### ISSUE TITLE
Error: Circuit not enabled!

### ISSUE THREAD

**Issue by JGAntunes** [libp2p/js-libp2p-ping#70]
Running a `ping` command using `libp2p-ping` out of the box in `js-ipfs`, to a peer id with whom our node doesn't have an established connection yet,  returns the following error:
```
Error: Circuit not enabled!
    at nextTransport (/usr/src/app/node_modules/libp2p-switch/src/dial.js:103:23)
    at attemptDial (/usr/src/app/node_modules/libp2p-switch/src/dial.js:93:7)
    at Switch.dial (/usr/src/app/node_modules/libp2p-switch/src/dial.js:32:9)
    at new Ping (/usr/src/app/node_modules/libp2p-ping/src/ping.js:26:11)
    at _getPeerInfo (/usr/src/app/node_modules/libp2p/src/index.js:281:22)
    at Immediate.setImmediate [as _onImmediate] (/usr/src/app/node_modules/libp2p/src/get-peer-info.js:46:24)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
Debug: internal, implementation, error 
    TypeError: p.start is not a function
    at self._libp2pNode.ping (/usr/src/app/src/core/components/ping.js:74:9)
    at _getPeerInfo (/usr/src/app/node_modules/libp2p/src/index.js:281:7)
    at Immediate.setImmediate (/usr/src/app/node_modules/libp2p/src/get-peer-info.js:46:24)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

Looking further seems that it's coming from here:
https://github.com/libp2p/js-libp2p-switch/blob/a4521ddef257f3de9fd763706082cae0df10cee7/src/dial.js#L103

This results in `ping` failing on the first few tries. Eventually it will be able to successfully ping the peer in question.

Haven't looked much into this, but does it mean we need to have the `EXPERIMENTAL.relay` feature enabled in order to use ping without any hiccups?

**Comment by dryajov** [comment]
In reality this is a very poorly worded message and it simply means that all dials failed including circuit. I'll create a PR to address this shortly, sorry for the inconvenience.

That said, it might indicate an issue somewhere else (including circuit). Are you able to connect to a peer at all with `ipfs swarm connect <PeerId>` (or equivalent code) using your branch/code?

**Comment by dryajov** [comment]
Here is the PR for improved error reporting functionality - https://github.com/libp2p/js-libp2p-switch/pull/250

**Comment by JGAntunes** [comment]
Thanks @dryajov! I'm away from my laptop but I'll check it as soon as I'm back. I'm almost certain I'm able to run `jsipfs swarm connect` but I'll confirm it. One thing that might be relevant though is that after the first/second time the ping actually works.

**Comment by JGAntunes** [comment]
Alright, thanks a lot @dryajov, made things a lot clearer to me. Closing this :+1:
